version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: trofei
      POSTGRES_USER: trofei_user
      POSTGRES_PASSWORD: trofei_pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php