version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: trofei
      POSTGRES_USER: trofei_user
      POSTGRES_PASSWORD: trofei_pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - trofei-network

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - trofei-network

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - trofei-network

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    working_dir: /app/tests
    command: npx playwright test
    depends_on:
      - nginx
      - php
      - db
    networks:
      - trofei-network

networks:
  trofei-network:
    driver: bridge